name: Swift Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Run Tests
        run: swift test
